name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::868683861378:role/CsiLandingPageStack-DeploymentRoleC7BBCF2C-G5GPTVAXXMMW
          aws-region: us-east-1
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version-file: ".node-version"
      - run: make deploy
